name: CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1.checkou master
        uses: actions/checkout@v3
        
      - name: 2.copy favicon.ico 
        run: cp ./favicon.ico ./public
        
      - name: 3.tar public folder
        run: tar -zcvf public.tar.gz public
        
      - name: 4.sync to server 
        uses: Creepios/sftp-action@v1.0.4
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASS_WORD }}
          localPath: ./public.tar.gz
          remotePath: /web/static/www.cybeor.com/
         
      - name: 5.ssh and deploy 
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USER_NAME }}
         key: ${{ secrets.PRIVATE_KEY }}
         port: 22
         script: |
          cd /web/static/www.cybeor.com/
          rm -rf *
          tar -zxvf public.tar.gz  --strip-components 1
          rm public.tar.gz
          echo deploy done...
